ci: add helm-workflows (#63)
* ci(helm-docs): add workflow to auto-generate chart README

* ci(helm-push): update workflow

* ci(helm-lint): add workflow to lint charts

* ci(helm-chart-version-update): add workflow to check if chart version has been updated

* ci(helm-schema): add workflow to generate values schema

diff --git a/.github/workflows/helm-schema.yaml b/.github/workflows/helm-schema.yaml
--- a/.github/workflows/helm-schema.yaml
+++ b/.github/workflows/helm-schema.yaml
@@ -1,18 +1,19 @@
 ---
 # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
-name: Helm Push
-permissions: { contents: read }
+name: Helm Schema
+permissions: { contents: write }
 
 on:
   workflow_dispatch:
     inputs:
       dry-run:
         description: Dry Run
-        default: false
+        default: true
         required: false
         type: boolean
   push:
-    paths: ["charts/**"]
+    paths:
+      - "charts/**/values.yaml"
 
 jobs:
   discover-charts:
@@ -30,41 +31,68 @@ jobs:
           echo "charts=${CHARTS}" >> "$GITHUB_OUTPUT"
           echo "Found charts: ${CHARTS}"
 
-  helm-push:
-    needs: discover-charts
+  generate-schema:
+    needs: [discover-charts]
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
         chart: ${{ fromJson(needs.discover-charts.outputs.charts) }}
     steps:
+      - name: Generate Token
+        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
+        id: app-token
+        with:
+          app-id: "${{ secrets.BOT_APP_ID }}"
+          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
+
       - name: Checkout
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          token: "${{ steps.app-token.outputs.token }}"
 
       - name: Get Changed Files
         id: changed-files
         uses: bjw-s-labs/action-changed-files@b1144fc772fca235a50902c7bb6cc431cc7d8e27 # v0.3.2
         with:
-          patterns: "./charts/${{ matrix.chart }}/Chart.yaml" # Trigger on version change in Chart.yaml
+          patterns: |
+            ./charts/${{ matrix.chart }}/Chart.yaml
+            ./charts/${{ matrix.chart }}/values.yaml
+            ./charts/${{ matrix.chart }}/README.md.gotmpl
 
       - name: Setup mise
         if: steps.changed-files.outputs.changed_files != '[]' || github.event_name == 'workflow_dispatch'
         uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1
 
-      - name: Package Helm chart
+      - name: Generate helm schema
         if: steps.changed-files.outputs.changed_files != '[]' || github.event_name == 'workflow_dispatch'
         working-directory: ./charts/${{ matrix.chart }}
-        run: helm package .
+        run: mise exec -- helm-schema
 
-      - name: Helm login to GHCR
-        if: steps.changed-files.outputs.changed_files != '[]' || github.event_name == 'workflow_dispatch'
-        run: |
-          echo ${{ secrets.GHCR_RW_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
-
-      - name: Push Helm chart to GHCR
+      - name: Commit and push changes
         if: |
           (steps.changed-files.outputs.changed_files != '[]' && github.ref_name == 'main')
           ||
           ( github.event_name == 'workflow_dispatch' && inputs.dry-run == false)
-        working-directory: ./charts/${{ matrix.chart }}
-        run: helm push "$(ls ./*.tgz)" oci://ghcr.io/${{ github.repository }}
+        env:
+          CI_AUTHOR_NAME: "mr-borboto[bot]"
+          CI_AUTHOR_EMAIL: "170036086+mr-borboto[bot]@users.noreply.github.com"
+          CI_COMMIT_MESSAGE: "chore(chart/${{ matrix.chart }}): update values schema"
+        run: |
+          git config --global user.name '${{ env.CI_AUTHOR_NAME }}'
+          git config --global user.email '${{ env.CI_AUTHOR_EMAIL }}'
+          git add ./charts/${{ matrix.chart }}/values.schema.json
+          git commit -m "${{ env.CI_COMMIT_MESSAGE }}" && git push || echo "No changes to commit"
+
+  update-summary:
+    needs: generate-schema
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Set Job Status
+        run: |
+          if [[ "${{ needs.generate-schema.result }}" == "success" ]]; then
+            echo "Helm schemas successfully updated!"
+          else
+            echo "::warning::Some charts failed to update schemas. Check job logs for details."
+          fi
